### ISSUE TITLE
How to customize

### ISSUE THREAD

**Issue by mehulkundu** [xtendui/xtendui#65]
## Suggestion

How to customize the themes in terms of  - colors, padding, border, radius, font family? etc.
And there's already a limited collection of button type how can we extend that?

Like if you see the design system of vercel they at least have 2 - 3 type of button like - Primary, Ghost, With gradient, with custom SVG, loading state etc. https://vercel.com/design/button

So it could be possible if I can just extend this library to customize it. But the question is, Is it possible?

**Comment by minimit** [comment]
Hello, thanks for the suggestion.

In the demos there are different examples of **variants** and **sizes** see [button](https://xtendui.com/components/button/content) for example. The code is highlighted on the relevant classes that give that particular style.

Xtend UI doesn't have a real theme (it's done for custom frontend development) but you can modify the colors and size and all the visuals by using different **tailwind classes** and **tailwind theme variables**.

I suggest creating global variables for the style you want to reuse (for example `button.sizeMd`) and reusing that variable.
