### ISSUE TITLE
vanilla js theme example using codepen or jsfiddle

### ISSUE THREAD

**Issue by c-nv-s** [xtendui/xtendui#72]
Is it possible to show a quick codepen or jsfiddle example of one of the more complex theme examples just with vanilla js.

it is not clear to me how you are importing the js in the examples on the site.

thanks

**Comment by c-nv-s** [comment]
@minimit any chance of a quick look at my request?

**Comment by minimit** [comment]
Hello it should be possible by removing the imports and using all the js with the cdn for examples on codepen
`https://unpkg.com/browse/xtendui@1.1.0/dist/`

**Comment by c-nv-s** [comment]
Just tried to do that with the "Blocks Featured V1" theme
https://jsfiddle.net/8ued3jb5/

doesn't seem to work

**Comment by minimit** [comment]
Updated https://jsfiddle.net/9juw32px/6/
