### ISSUE TITLE
Amend the docs for the hero component.

### ISSUE THREAD

**Issue by johnkelaita** [xtendui/xtendui#96]
## Suggestion

Amend the docs for the hero component.

In order to support images that are smaller than the dimensions of the parent container (consider a 1024x1024 image within a fullscreen container on a 4K monitor), you'll need to amend the hero CSS classes...

`xt-media object-cover w-full h-full`

This simple amendment should do it.

This applied to all of the examples on the [docs](https://xtendui.com/components/hero/)

**Comment by minimit** [comment]
Hello thanks for the feedback.

I've checked and `xt-media` already has `width: 100%;` and `height: 100%;` and they gets stretched with big resolutions.

Probably in your settings you have not set up `content:` inside `tailwind.config.js` and so `xt-media` css isn't compiled.

**Comment by johnkelaita** [comment]
You're correct, it was a configuration error on my part. Thank you for your help, great components!
